alpha: 2.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/choi/ASPC/results_wpc/hme_s2_wpc-halfcheetah-medium-expert-v2-29d0451d
device: cuda
discount: 0.99
env: halfcheetah-medium-expert-v2
eval_freq: 20000
expl_noise: 0.1
group: wpc_locomotion
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: hme_s2_wpc-halfcheetah-medium-expert-v2-29d0451d
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: ASPC_WPC_FULL
seed: 2
tau: 0.005
