batch_size: 256
hidden_dim: 512
discount: 0.99
tau: 0.005
actor_lr: 0.0003
critic_lr: 0.0003
max_steps: 1000000
normalize: true
reward_transform: none
eval_freq: 20000
eval_episodes: 10
eval_seed: null
eval_first_step: 20000
final_eval_repeats: 5
action_clip_eps: 1.0e-05
actor_depth: 4
critic_depth: 4
critic_layernorm: true
actor_layernorm: false
ln_eps: 1.0e-06
flow_lr: 0.0003
flow_steps: 10
normalize_q_loss: true
q_agg: mean
policy_freq: 1
alpha_E: 10.0
alpha_B: 10.0
alpha_lr: 0.002
meta_interval: 20
outer_batch_size: 256
smoothness_eps: 1.0e-06
algorithm: fql_amo
