alpha_B: 2.0
alpha_E: 2.0
alpha_freq: 10
alpha_lr: 0.0003
adaptive_multiscale: true
batch_size: 256
bootstrap_outer_loss_version: tq_detached_rms_target_v1
bootstrap_rms_diagnostic_freq: 0
buffer_size: 10000000
checkpoints_path: /home/choi/AMO_EXP/results/td3_amo_antmaze_te1_tlr_main_fill_adaptive_critic/runs/td3amo_te1_tb1_tlr3e-4_amu_s2-antmaze-umaze-v2-927f8ed3
critic_hidden_dim: 256
critic_layernorm: true
critic_n_hiddens: 3
device: cuda
discount: 0.99
env: antmaze-umaze-v2
eval_freq: 5000
expl_noise: 0.1
final_eval_repeats: 5
group: td3amo-antmaze-te1-tlr-main-fill-adaptive-critic
load_model: ''
max_timesteps: 1000000
metrics_log_freq: 200
n_episodes: 100
name: td3amo_te1_tb1_tlr3e-4_amu_s2-antmaze-umaze-v2-927f8ed3
noise_clip: 0.5
normalize: true
normalize_reward: true
policy_freq: 2
policy_noise: 0.2
profile_runtime: false
project: AMO-antmaze-te1-tlr
proximal_n_steps: 1
resume_tag: ''
save_freq: 5000
seed: 2
smoothness_eps: 1.0e-06
smoothness_max: null
tau: 0.005
