T_B: 1.0
T_E: 1.0
T_freq: 10
T_lr: 0.002
adaptive_multiscale: true
batch_size: 256
bootstrap_outer_loss_version: tq_detached_rms_target_v1
bootstrap_rms_diagnostic_freq: 0
buffer_size: 10000000
checkpoints_path: /raid/ext_csv/AMO_store/amo_adaptive_multiscale_antmaze6_scale_sweep_seed0/runs/amo_ams_umaze-div_Te1_Tb1_s0-antmaze-umaze-diverse-v2-c6a40782
device: cuda
discount: 0.99
env: antmaze-umaze-diverse-v2
eval_freq: 20000
expl_noise: 0.1
group: amo-antmaze6-scale-sweep-seed0
load_model: ''
max_timesteps: 1000000
metrics_log_freq: 200
n_episodes: 10
name: amo_ams_umaze-div_Te1_Tb1_s0-antmaze-umaze-diverse-v2-c6a40782
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
profile_runtime: false
project: AMO-adaptive-multiscale
proximal_n_steps: 1
resume_tag: amo_ams_umaze-div_Te1_Tb1_s0
save_freq: 20000
seed: 0
smoothness_eps: 1.0e-06
smoothness_max: null
tau: 0.005
