T_B: 5.0
T_E: 5.0
T_freq: 10
T_lr: 0.001
adaptive_multiscale: true
batch_size: 256
bootstrap_outer_loss_version: tq_detached_rms_target_v1
bootstrap_rms_diagnostic_freq: 0
buffer_size: 10000000
checkpoints_path: /raid/ext_csv/AMO_store/amo_adaptive_multiscale_loco9_te_tb_tlr_grid_seed0/runs/amo_ams_hc-m_Te5_Tb5_Tlr0p001_s0-halfcheetah-medium-v2-ebf847ef
critic_hidden_dim: 256
critic_layernorm: true
critic_n_hiddens: 3
device: cuda
discount: 0.99
env: halfcheetah-medium-v2
eval_freq: 5000
expl_noise: 0.1
group: amo-loco9-te-tb-tlr-grid-seed0
load_model: ''
max_timesteps: 1000000
metrics_log_freq: 200
n_episodes: 10
name: amo_ams_hc-m_Te5_Tb5_Tlr0p001_s0-halfcheetah-medium-v2-ebf847ef
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
profile_runtime: false
project: AMO-adaptive-multiscale
proximal_n_steps: 1
resume_tag: amo_ams_hc-m_Te5_Tb5_Tlr0p001_s0
save_freq: 5000
seed: 0
smoothness_eps: 1.0e-06
smoothness_max: null
tau: 0.005
