alpha: 2.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/choi/ASPC/results/td3bc_aspc_table6/runs/td3bc_aspc_hm_s0-hopper-medium-v2-4ca5f2d3
device: cuda
discount: 0.99
env: hopper-medium-v2
eval_freq: 5000
expl_noise: 0.1
group: td3bc-aspc-table6
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: td3bc_aspc_hm_s0-hopper-medium-v2-4ca5f2d3
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: ASPC-td3bc
seed: 0
tau: 0.005
