alpha: 2.5
alpha_freq: 10
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/shchoi/ASPC/results_pi_l3/wm_s0_aspc-walker2d-medium-v2-09e74ee1
device: cuda
discount: 0.99
ema_alpha: 0.995
env: walker2d-medium-v2
eval_freq: 20000
expl_noise: 0.1
group: pi_l3_sweep
l3_mode: aspc
load_model: ''
loss_function: 4
max_timesteps: 1000000
metrics_log_freq: 200
n_episodes: 10
name: wm_s0_aspc-walker2d-medium-v2-09e74ee1
noise_clip: 0.5
normalize: true
normalize_reward: false
pi_l3_L_max: null
pi_l3_eps_L: 1.0e-06
policy_freq: 2
policy_noise: 0.2
project: ASPC_PI_L3
save_freq: 200000
seed: 0
tau: 0.005
