alpha: 2.5
alpha_freq: 10
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/svcho/amo/results_pi_only_antmaze/ammp_s0_pi_only_smoke-antmaze-medium-play-v2-545a27cb
device: cuda
discount: 0.99
ema_alpha: 0.995
env: antmaze-medium-play-v2
eval_freq: 2500
expl_noise: 0.1
group: pi_only_antmaze
l3_mode: pi_only
load_model: ''
loss_function: 4
max_timesteps: 5000
metrics_log_freq: 200
n_episodes: 10
name: ammp_s0_pi_only_smoke-antmaze-medium-play-v2-545a27cb
noise_clip: 0.5
normalize: true
normalize_reward: true
pi_l3_L_max: null
pi_l3_eps_L: 1.0e-06
policy_freq: 2
policy_noise: 0.2
project: ASPC_PI_L3
save_freq: 0
seed: 0
tau: 0.005
