T: 1.25
T_freq: 10
T_lr: 0.0002
adaptive_multiscale: true
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/ext_csh/APART/results/adaptive_multiscale_locomotion12_seed0/runs/adaptive_multiscale_hc-mr_s0-halfcheetah-medium-replay-v2-f8e30c31
device: cuda
discount: 0.99
dual_proximal: true
env: halfcheetah-medium-replay-v2
eval_freq: 5000
expl_noise: 0.1
group: locomotion12-seed0-n4
load_model: ''
max_timesteps: 1000000
metrics_log_freq: 200
n_episodes: 10
name: adaptive_multiscale_hc-mr_s0-halfcheetah-medium-replay-v2-f8e30c31
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
profile_runtime: false
project: APART-adaptive-multiscale
proximal_n_steps: 4
resume_tag: ''
save_freq: 5000
seed: 0
smoothness_eps: 1.0e-06
smoothness_max: null
tau: 0.005
