alpha: 2.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/shchoi/ASPC/results_wpc/wm_s0_wpc-walker2d-medium-v2-0be6dd81
device: cuda
discount: 0.99
env: walker2d-medium-v2
eval_freq: 20000
expl_noise: 0.1
group: wpc_locomotion
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: wm_s0_wpc-walker2d-medium-v2-0be6dd81
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: ASPC_WPC_FULL
seed: 0
tau: 0.005
