alpha: 2.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/ext_csh/benchmark/results/wpc/halfcheetah-medium-v2/seed0/s0-halfcheetah-medium-v2-c0d9395d
device: cuda
discount: 0.99
env: halfcheetah-medium-v2
eval_freq: 5000
expl_noise: 0.1
group: wpc
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: s0-halfcheetah-medium-v2-c0d9395d
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.1
project: ASPC
seed: 0
tau: 0.005
