name: IQLAdaptiveBeta
algorithm: iql_adaptive_beta
env: halfcheetah-medium-replay-v2
seed: 2
rho_lr: 0.0003
beta: 3.0
beta_initial: 3.0
beta_fixed: 3.0
adaptive_enabled: true
max_timesteps: 1000000
eval_freq: 5000
batch_size: 256
discount: 0.99
tau: 0.005
iql_tau: 0.7
normalize: true
normalize_reward: false
actor_lr: 0.0003
qf_lr: 0.0003
vf_lr: 0.0003
project: CORL
group: iql_amo_shchoi69_rho3e-04
