alpha: 2.5
alpha_freq: 10
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/choi/amo/results_pi_only_xfit_target_mpi_nstep/hme_s0_pi_only_xfit_target_mpi_n2_smoke20000-hopper-medium-expert-v2-a1223e3d
device: cuda
discount: 0.99
ema_alpha: 0.995
env: hopper-medium-expert-v2
eval_freq: 20000
expl_noise: 0.1
group: pi_only_xfit_target_mpi_nstep
l3_mode: pi_only_xfit_target_mpi_nstep
load_model: ''
loss_function: 4
max_timesteps: 20000
metrics_log_freq: 200
n_episodes: 10
name: hme_s0_pi_only_xfit_target_mpi_n2_smoke20000-hopper-medium-expert-v2-a1223e3d
noise_clip: 0.5
normalize: true
normalize_reward: false
pi_l3_L_max: null
pi_l3_eps_L: 1.0e-06
policy_freq: 2
policy_noise: 0.2
profile_runtime: true
project: AMO
proximal_n_steps: 2
resume_tag: ''
save_freq: 20000
seed: 0
tau: 0.005
