T: 1.25
T_freq: 10
T_lr: 0.0002
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/ext_csh/APART/results/dual_n24_adroit/runs/pen_dual_N2_T1.25_Tlr2e-4_s0-pen-cloned-v1-2befec34
device: cuda
discount: 0.99
dual_proximal: true
env: pen-cloned-v1
eval_freq: 20000
expl_noise: 0.1
group: dual-n24
load_model: ''
max_timesteps: 1000000
metrics_log_freq: 200
n_episodes: 10
name: pen_dual_N2_T1.25_Tlr2e-4_s0-pen-cloned-v1-2befec34
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
profile_runtime: false
project: APART-adroit-dual
proximal_n_steps: 2
resume_tag: ''
save_freq: 0
seed: 0
smoothness_eps: 1.0e-06
smoothness_max: null
tau: 0.005
