batch_size: 256
hidden_dim: 256
discount: 0.99
tau: 0.005
actor_lr: 0.0003
critic_lr: 0.0003
max_steps: 1000000
normalize: true
reward_transform: antmaze_shift
eval_freq: 20000
eval_episodes: 10
eval_seed: null
eval_first_step: 20000
final_eval_repeats: 1
final_eval_episodes: 50
actor_depth: 2
critic_depth: 2
critic_layernorm: false
gaussian: true
value_depth: 2
value_lr: 0.0003
expectile: 0.9
beta: 10.0
weight_cap: 100.0
policy_freq: 1
algorithm: iql
