alpha_B: 2.0
alpha_E: 2.0
alpha_freq: 10
alpha_lr: 0.001
adaptive_multiscale: true
batch_size: 256
bootstrap_outer_loss_version: tq_detached_rms_target_v1
bootstrap_rms_diagnostic_freq: 0
buffer_size: 10000000
checkpoints_path: /home/ext_csh/AMO/results/amo_loco9_te1_tb1_tlr1e-3_seeds0to3/runs/amo_adaptive_multiscale_hc-m_s1_tlr1e-3_te1_tb1-halfcheetah-medium-v2-f1a70d99
critic_hidden_dim: 256
critic_layernorm: true
critic_n_hiddens: 3
device: cuda
discount: 0.99
env: halfcheetah-medium-v2
eval_freq: 5000
expl_noise: 0.1
group: amo-loco9-te1-tb1-tlr1e-3-seeds0to3
load_model: ''
max_timesteps: 1000000
metrics_log_freq: 200
n_episodes: 10
name: amo_adaptive_multiscale_hc-m_s1_tlr1e-3_te1_tb1-halfcheetah-medium-v2-f1a70d99
noise_clip: 0.5
normalize: true
normalize_q: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
profile_runtime: false
project: AMO-adaptive-multiscale
proximal_n_steps: 1
resume_tag: amo_adaptive_multiscale_hc-m_s1_tlr1e-3_te1_tb1
save_freq: 5000
seed: 1
smoothness_eps: 1.0e-06
smoothness_max: null
tau: 0.005
