T: 1.25
T_freq: 10
T_lr: 0.0002
adaptive_bootstrap_scale: true
batch_size: 256
bootstrap_stability_budget: 0.05
buffer_size: 10000000
checkpoints_path: /home/ext_csh/APART/results/adaptive_bootstrap_locomotion12_seed0_unconstrained/runs/adaptive_bootstrap_hc-r_s0-halfcheetah-random-v2-90a8969f
constrain_T_B_le_T_E: false
device: cuda
discount: 0.99
dual_proximal: true
env: halfcheetah-random-v2
eval_freq: 20000
expl_noise: 0.1
group: locomotion12-seed0-unconstrained
load_model: ''
max_timesteps: 1000000
metrics_log_freq: 200
n_episodes: 10
name: adaptive_bootstrap_hc-r_s0-halfcheetah-random-v2-90a8969f
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
profile_runtime: false
project: APART-adaptive-bootstrap
proximal_n_steps: 1
resume_tag: ''
save_freq: 20000
seed: 0
smoothness_eps: 1.0e-06
smoothness_max: null
tau: 0.005
