T: 1.25
T_freq: 10
T_lr: 0.0002
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/choi/APART/results_apart/hcr_s0_apart_n4_dual-halfcheetah-medium-replay-v2-7d04d354
device: cuda
discount: 0.99
dual_proximal: true
env: halfcheetah-medium-replay-v2
eval_freq: 20000
expl_noise: 0.1
group: apart_hcr_n4_dual
load_model: ''
max_timesteps: 1000000
metrics_log_freq: 200
n_episodes: 10
name: hcr_s0_apart_n4_dual-halfcheetah-medium-replay-v2-7d04d354
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
profile_runtime: false
project: APART
proximal_n_steps: 4
resume_tag: ''
save_freq: 200000
seed: 0
smoothness_eps: 1.0e-06
smoothness_max: null
tau: 0.005
