alpha: 2.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/ext_csh/benchmark/results/wpc/hopper-expert-v2/seed1/s1-hopper-expert-v2-bc5f98ee
device: cuda
discount: 0.99
env: hopper-expert-v2
eval_freq: 5000
expl_noise: 0.1
group: wpc
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: s1-hopper-expert-v2-bc5f98ee
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.1
project: ASPC
seed: 1
tau: 0.005
