T: 1.25
T_freq: 10
T_lr: 0.0001
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/ext_csh/APART/results/n1_pen_cloned/runs/pen-cloned_N1_T1.25_Tlr1e-4_g0.999_s0-pen-cloned-v1-6b9bbe60
device: cuda
discount: 0.999
env: pen-cloned-v1
eval_freq: 20000
expl_noise: 0.1
group: pen-cloned-n1-g999
load_model: ''
max_timesteps: 1000000
metrics_log_freq: 200
n_episodes: 10
name: pen-cloned_N1_T1.25_Tlr1e-4_g0.999_s0-pen-cloned-v1-6b9bbe60
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
profile_runtime: false
project: APART-adroit-n1
proximal_n_steps: 1
resume_tag: ''
save_freq: 0
seed: 0
smoothness_eps: 1.0e-06
smoothness_max: null
tau: 0.005
