T: 1.25
T_freq: 10
T_lr: 0.0002
adaptive_multiscale: true
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/ext_csh/APART/results/adaptive_multiscale_locomotion9_seed0/runs/adaptive_multiscale_w-me_s0-walker2d-medium-expert-v2-b576b530
device: cuda
discount: 0.99
env: walker2d-medium-expert-v2
eval_freq: 5000
expl_noise: 0.1
group: locomotion9-seed0
load_model: ''
max_timesteps: 1000000
metrics_log_freq: 200
n_episodes: 10
name: adaptive_multiscale_w-me_s0-walker2d-medium-expert-v2-b576b530
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
profile_runtime: false
project: APART-adaptive-multiscale
project_T_B_to_T_E: true
proximal_n_steps: 1
resume_tag: ''
save_freq: 5000
seed: 0
smoothness_eps: 1.0e-06
smoothness_max: null
tau: 0.005
