alpha: 2.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: /home/choi/ASPC/results_wpc/hopm_s3_wpc-hopper-medium-v2-cb0e020a
device: cuda
discount: 0.99
env: hopper-medium-v2
eval_freq: 20000
expl_noise: 0.1
group: wpc_locomotion
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: hopm_s3_wpc-hopper-medium-v2-cb0e020a
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: ASPC_WPC_FULL
seed: 3
tau: 0.005
